language: php

php:
  - 5.4

services:
  - mongodb

before_install: phpenv config-add .travis.php.ini

install:
  - composer install
  - composer require codeclimate/php-test-reporter:dev-master

before_script: mkdir -p build/logs

script: phpunit --configuration ./tests/phpunit.xml --coverage-clover ./build/logs/clover.xml

after_script:
  - CODECLIMATE_REPO_TOKEN=2daa3684fc65b0b443966c6c3ae4ddafc81aba296d0bac7085a3d0ede1a2aeb6 ./vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"